name: Commit Verification

on: [push]

jobs:
 commit-verification:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Install gitsign
       run: |
         wget https://github.com/sigstore/gitsign/releases/download/v0.7.1/gitsign_0.7.1_linux_amd64.deb
         sudo dpkg -i gitsign_0.7.1_linux_amd64.deb

     - name: Verify Commit Signature
       run: |
         # Fetch all commits in the current push
         git rev-list HEAD > commits.txt

         # Iterate over each commit and verify the signature
         while read -r commit; do
           gitsign verify-commit "$commit" || {
             echo "Commit $commit is not signed. Please sign all commits before pushing."
             exit 1
           }
         done < commits.txt
